#!/bin/bash

VERBOSE=0

REMOTE_DONSTRO_ROOT=${DONSTRO_ROOT:-donstro}

. donstro/donstro.env


remote_app_root() {
  echo ${REMOTE_DONSTRO_ROOT}/${APP_NAME}
}

local_compose_file() {
  echo donstro/docker-compose.yml
}

remote_secrets() {
  local secrets_file=donstro/remote.secrets
  local secrets_encr=${secrets_file}.gpg
  if [ ! -f ${secrets_file} ]
  then
    [[ -f ${secrets_encr} ]] || return
    gpg --output ${secrets_file} --decrypt ${secrets_encr}
  fi
  cat ${secrets_file} | xargs
}

remote_compose_file() {
  echo $(remote_app_root)/docker-compose.yml
}

remote_non_secrets() {
  local env_file=donstro/remote.env
  if [ -f ${env_file} ]
  then
    cat ${env_file} | xargs
  else
    echo ''
  fi
}

environment() {
  echo $(remote_secrets) $(remote_non_secrets)
}

is_verbose() {
  [[ $VERBOSE == 1 ]]
}

run() {
  [[ $VERBOSE == 1 ]] && echo running "$@"
  $@
}

remote() {
  [[ $VERBOSE == 1 ]] && echo running_remote "$@"
  eval "ssh ${USER}@${HOST} -t $@"
}

ensure_remote_compose_file() {
  remote mkdir -p $(remote_app_root)
  run scp $(local_compose_file) ${USER}@${HOST}:$(remote_compose_file)
}

remote_compose() {
  ensure_remote_compose_file
  remote "$(environment) docker compose -f $(remote_compose_file) $@"
}

remote_compose_run() {
  remote_compose run --rm $@
}

setup_remote_donstro() {
  local app_name=$1
  remote_compose_run $app_name $SETUP_APP
}
remote_docker_login() {
  remote '"aws ecr get-login --no-include-email | sh"'
}
usage() {
  cat << EOUSAGE
  usage: options $0 command [args]

  where command is one of
  - login                           : login in to docker on remote machine
  - setup service_name              : setup donstro remotely and setup your app
  - up    service_name              : set the remote service up
  - run   service_name [parameters] : run a command in your remote container
  - rake  service_name [parameters] : run a rake task in your remote container
  - or any other docker-compose commmand

 and options is one of
  - --verbose|-v                   : show what we're doing

EOUSAGE
  exit 0
}


while [[ $1 == -* ]]; do
  case $1 in
    --verbose)
      shift
      VERBOSE=1
      ;;
    -v)
      shift
      VERBOSE=1
      ;;
    --help)
      usage
      ;;
    -h)
      usage
      ;;
    *)
      usage
      ;;
  esac
done

command=$1

case $command in
  login)
    remote_docker_login
    ;;
  setup)
    shift
    setup_remote_donstro $1
    ;;
  up)
    shift
    remote_compose up -d $1
    ;;
  run)
    shift
    remote_compose_run $@
    ;;
  rake)
    shift
    remote_compose_run rake $@
    ;;
  *)
    remote_compose "$@"
    ;;
esac

